name: Stop, Build, dan Jalankan Ulang Aplikasi Go

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Langkah ini akan mencari dan menghentikan proses 'pk-fiber.exe' yang sedang berjalan.
      # Taskkill adalah perintah Windows untuk menghentikan proses.
      - name: Stop running Go application
        run: |
          taskkill /IM "pk-fiber.exe" /F || exit 0
        shell: cmd

      - name: Lakukan Build Aplikasi Go
        # Perintah ini akan mengompilasi ulang kode Anda menjadi file biner yang baru.
        run: |
          go mod tidy
          go build -o pk-fiber.exe

      - name: Jalankan Aplikasi Go yang Baru
        # Perintah ini akan menjalankan server Go yang sudah di-build,
        # dan akan terus berjalan.
        # Catatan: Job ini tidak akan selesai sampai Anda menghentikan proses secara manual.
        run: |
          start pk-fiber.exe
        shell: cmd

      - name: Pesan Sukses Deployment
        run: echo "Deployment selesai, aplikasi Go yang baru sudah berjalan."
