name: Deploy to csxpk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: jauharimalik/sapapi
          token: ${{ secrets.GITHUB_TOKEN }}
          # set-safe-directory: true sudah otomatis di v4

      - name: Stop all running Node.js processes
        continue-on-error: true
        run: taskkill /F /IM node.exe /T

      - name: Install dependencies
        run: npm install

      - name: Start all Node.js applications
        shell: cmd
        run: |
          start /b node server.js
          start /b node guling.js
          start /b node retur.js
          start /b node rijek.js
          start /b node sto.js
          start /b node grpo.js