name: Deploy to csxpk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: jauharimalik/sapapi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Restart and Start Node.js applications with PM2
        shell: cmd
        run: |
          pm2 start grpo.js --name "grpo-service" --watch --ignore-watch "node_modules"
          pm2 start guling.js --name "guling-service" --watch --ignore-watch "node_modules"
          pm2 start retur.js --name "retur-service" --watch --ignore-watch "node_modules"
          pm2 start rijek.js --name "rijek-service" --watch --ignore-watch "node_modules"
          pm2 start sto.js --name "sto-service" --watch --ignore-watch "node_modules"
          pm2 start server.js --name "server-service" --watch --ignore-watch "node_modules"

      - name: Save PM2 process list
        run: pm2 save

      - name: Show PM2 process status
        run: pm2 list