# .github/workflows/monitor.yml
name: PM2 Service Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false # Mengabaikan submodule untuk mencegah error
      - name: Add npm global to PATH
        run: echo "C:\Users\PROGRAM-002\AppData\Roaming\npm" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
        shell: powershell
      
      - name: Show PM2 process status
        run: pm2 list